# Generated by Django 2.1.3 on 2018-12-08 16:37

from django.db import migrations, models
import django.db.models.deletion
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.UUIDField(auto_created=True)),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('contracts', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('expire_date', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('site_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateTimeField()),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pay_type', models.CharField(max_length=10)),
                ('remark', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Client')),
            ],
        ),
    ]
